package generator

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
	"time"

	"github.com/zero-day-ai/gibson/cmd/taxonomy-gen/schema"
)

// GenerateHelpers generates SDK helper functions for creating nodes.
func GenerateHelpers(taxonomy *schema.Taxonomy, outputPath, pkgName string) error {
	tmpl, err := template.New("helpers").Funcs(helpersFuncMap()).Parse(helpersTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	data := struct {
		*schema.Taxonomy
		Package     string
		SourcePath  string
		GeneratedAt string
	}{
		Taxonomy:    taxonomy,
		Package:     pkgName,
		SourcePath:  "taxonomy/core.yaml",
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

func helpersFuncMap() template.FuncMap {
	return template.FuncMap{
		"toPascalCase": toPascalCase,
		"toCamelCase":  toCamelCase,
		"isRoot":       func(nt schema.NodeType) bool { return nt.Parent == nil },
		"hasParent":    func(nt schema.NodeType) bool { return nt.Parent != nil },
		"parentRefField": func(nt schema.NodeType) string {
			if nt.Parent == nil {
				return ""
			}
			// e.g., port has parent host, so ref_field is "host_id"
			// The protobuf field is "parent_host_id", but in Go we copy to "HostId"
			return toPascalCase(nt.Parent.Type) + "Id"
		},
		"requiredParams": func(nt schema.NodeType) string {
			var params []string
			for _, p := range nt.Properties {
				if p.Required {
					paramName := escapeKeyword(p.Name)
					params = append(params, fmt.Sprintf("%s %s", paramName, p.GoType()))
				}
			}
			return strings.Join(params, ", ")
		},
		"requiredParamsWithParent": func(nt schema.NodeType) string {
			var params []string
			// First parameter is parent
			if nt.Parent != nil {
				params = append(params, fmt.Sprintf("parent *taxonomypb.%s", toPascalCase(nt.Parent.Type)))
			}
			// Then required properties
			for _, p := range nt.Properties {
				if p.Required {
					paramName := escapeKeyword(p.Name)
					params = append(params, fmt.Sprintf("%s %s", paramName, p.GoType()))
				}
			}
			return strings.Join(params, ", ")
		},
		"requiredAssignments": func(nt schema.NodeType) []string {
			var assignments []string
			for _, p := range nt.Properties {
				if p.Required {
					paramName := escapeKeyword(p.Name)
					assignments = append(assignments, fmt.Sprintf("\t\t%s: %s,", toPascalCase(p.Name), paramName))
				}
			}
			return assignments
		},
		"escapeKeyword": escapeKeyword,
	}
}

const helpersTemplate = `// Code generated by taxonomy-gen from taxonomy YAML. DO NOT EDIT.
// Source: {{.SourcePath}}
// Taxonomy Version: {{.Version}}
// Generated at: {{.GeneratedAt}}

package {{.Package}}

import (
	"github.com/google/uuid"
	"github.com/zero-day-ai/sdk/api/gen/taxonomypb"
)

// ==================== NODE CREATION HELPERS ====================
//
// These helpers auto-generate UUIDs and set up parent relationships.
// Use these instead of manually creating protobuf messages.
//
// Root types (no parent):
//   - NewHost(ip string) *taxonomypb.Host
//   - NewDomain(name string) *taxonomypb.Domain
//   - etc.
//
// Child types (has parent):
//   - NewPort(parent *taxonomypb.Host, number int32, protocol string) *taxonomypb.Port
//   - NewService(parent *taxonomypb.Port, name string) *taxonomypb.Service
//   - etc.
//
// All helpers:
//   1. Generate a UUID and assign to Id field
//   2. Set required properties
//   3. For child types: copy parent.Id to the parent reference field
//   4. Panic if parent.Id is nil (must use NewXxx() or set Id manually)
//
{{range .NodeTypes}}
{{- if isRoot .}}
// New{{.Name | toPascalCase}} creates a {{.Name | toPascalCase}} with auto-generated UUID.
{{- if gt (len .RequiredProperties) 0}}
func New{{.Name | toPascalCase}}({{requiredParams .}}) *taxonomypb.{{.Name | toPascalCase}} {
	id := uuid.New().String()
	return &taxonomypb.{{.Name | toPascalCase}}{
		Id: id,
{{- range requiredAssignments .}}
{{.}}
{{- end}}
	}
}
{{else}}
func New{{.Name | toPascalCase}}() *taxonomypb.{{.Name | toPascalCase}} {
	id := uuid.New().String()
	return &taxonomypb.{{.Name | toPascalCase}}{
		Id: id,
	}
}
{{- end}}
{{else}}
// New{{.Name | toPascalCase}} creates a {{.Name | toPascalCase}} linked to parent {{.Parent.Type | toPascalCase}}.
// Panics if parent.Id is empty.
func New{{.Name | toPascalCase}}({{requiredParamsWithParent .}}) *taxonomypb.{{.Name | toPascalCase}} {
	if parent.Id == "" {
		panic("parent {{.Parent.Type | toPascalCase}} must have Id set - use New{{.Parent.Type | toPascalCase}}() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.{{.Name | toPascalCase}}{
		Id: id,
		Parent{{parentRefField .}}: parent.Id,
{{- range requiredAssignments .}}
{{.}}
{{- end}}
	}
}
{{- end}}
{{end}}`
