// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: daemon.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectRequest initiates a client connection to the daemon.
type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_version is the version of the Gibson CLI client
	ClientVersion string `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	// client_id is an optional unique identifier for this client
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ConnectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// ConnectResponse returns connection metadata.
type ConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// daemon_version is the version of the running daemon
	DaemonVersion string `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	// session_id is a unique identifier for this client session
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// grpc_address is the address the daemon is listening on
	GrpcAddress   string `protobuf:"bytes,3,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectResponse) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

// PingRequest is an empty health check request.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

// PingResponse confirms the daemon is responsive.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp is the server time when the ping was received
	Timestamp     int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StatusRequest queries daemon status.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

// StatusResponse returns complete daemon status information.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// running indicates if the daemon is running (always true if responding)
	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	// pid is the process ID of the daemon
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// start_time is when the daemon started (Unix timestamp)
	StartTime int64 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// uptime is the human-readable uptime string
	Uptime string `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// grpc_address is the gRPC server address
	GrpcAddress string `protobuf:"bytes,5,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	// registry_type is the type of registry (embedded, external)
	RegistryType string `protobuf:"bytes,6,opt,name=registry_type,json=registryType,proto3" json:"registry_type,omitempty"`
	// registry_addr is the registry endpoint address
	RegistryAddr string `protobuf:"bytes,7,opt,name=registry_addr,json=registryAddr,proto3" json:"registry_addr,omitempty"`
	// callback_addr is the callback server address
	CallbackAddr string `protobuf:"bytes,8,opt,name=callback_addr,json=callbackAddr,proto3" json:"callback_addr,omitempty"`
	// agent_count is the number of registered agents
	AgentCount int32 `protobuf:"varint,9,opt,name=agent_count,json=agentCount,proto3" json:"agent_count,omitempty"`
	// mission_count is the total number of missions
	MissionCount int32 `protobuf:"varint,10,opt,name=mission_count,json=missionCount,proto3" json:"mission_count,omitempty"`
	// active_mission_count is the number of currently running missions
	ActiveMissionCount int32 `protobuf:"varint,11,opt,name=active_mission_count,json=activeMissionCount,proto3" json:"active_mission_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *StatusResponse) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *StatusResponse) GetRegistryType() string {
	if x != nil {
		return x.RegistryType
	}
	return ""
}

func (x *StatusResponse) GetRegistryAddr() string {
	if x != nil {
		return x.RegistryAddr
	}
	return ""
}

func (x *StatusResponse) GetCallbackAddr() string {
	if x != nil {
		return x.CallbackAddr
	}
	return ""
}

func (x *StatusResponse) GetAgentCount() int32 {
	if x != nil {
		return x.AgentCount
	}
	return 0
}

func (x *StatusResponse) GetMissionCount() int32 {
	if x != nil {
		return x.MissionCount
	}
	return 0
}

func (x *StatusResponse) GetActiveMissionCount() int32 {
	if x != nil {
		return x.ActiveMissionCount
	}
	return 0
}

// RunMissionRequest starts a mission execution.
type RunMissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// workflow_path is the path to the mission workflow YAML file
	WorkflowPath string `protobuf:"bytes,1,opt,name=workflow_path,json=workflowPath,proto3" json:"workflow_path,omitempty"`
	// mission_id is an optional custom mission identifier
	MissionId string `protobuf:"bytes,2,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	// variables contains workflow variables to override
	Variables     map[string]string `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunMissionRequest) Reset() {
	*x = RunMissionRequest{}
	mi := &file_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMissionRequest) ProtoMessage() {}

func (x *RunMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMissionRequest.ProtoReflect.Descriptor instead.
func (*RunMissionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *RunMissionRequest) GetWorkflowPath() string {
	if x != nil {
		return x.WorkflowPath
	}
	return ""
}

func (x *RunMissionRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *RunMissionRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

// MissionEvent represents a mission execution event.
type MissionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type identifies the type of event
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// timestamp is when the event occurred (Unix timestamp)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// mission_id is the unique mission identifier
	MissionId string `protobuf:"bytes,3,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	// node_id is the workflow node ID (if applicable)
	NodeId string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// message is a human-readable event message
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// data contains event-specific data (JSON-encoded)
	Data string `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// error contains error information if the event represents an error
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionEvent) Reset() {
	*x = MissionEvent{}
	mi := &file_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionEvent) ProtoMessage() {}

func (x *MissionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionEvent.ProtoReflect.Descriptor instead.
func (*MissionEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *MissionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MissionEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MissionEvent) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *MissionEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MissionEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MissionEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *MissionEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StopMissionRequest requests mission termination.
type StopMissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mission_id is the identifier of the mission to stop
	MissionId string `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	// force indicates whether to force-kill the mission (default: graceful)
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMissionRequest) Reset() {
	*x = StopMissionRequest{}
	mi := &file_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMissionRequest) ProtoMessage() {}

func (x *StopMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMissionRequest.ProtoReflect.Descriptor instead.
func (*StopMissionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *StopMissionRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *StopMissionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// StopMissionResponse confirms mission stop request.
type StopMissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates if the stop request was accepted
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional context
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMissionResponse) Reset() {
	*x = StopMissionResponse{}
	mi := &file_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMissionResponse) ProtoMessage() {}

func (x *StopMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMissionResponse.ProtoReflect.Descriptor instead.
func (*StopMissionResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *StopMissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopMissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListMissionsRequest queries mission list.
type ListMissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// active_only filters to only running missions
	ActiveOnly bool `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	// limit restricts the number of results
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// offset is the pagination offset
	Offset        int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissionsRequest) Reset() {
	*x = ListMissionsRequest{}
	mi := &file_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionsRequest) ProtoMessage() {}

func (x *ListMissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionsRequest.ProtoReflect.Descriptor instead.
func (*ListMissionsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *ListMissionsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListMissionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMissionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListMissionsResponse returns mission list.
type ListMissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// missions is the list of missions
	Missions []*MissionInfo `protobuf:"bytes,1,rep,name=missions,proto3" json:"missions,omitempty"`
	// total is the total count of missions (for pagination)
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissionsResponse) Reset() {
	*x = ListMissionsResponse{}
	mi := &file_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionsResponse) ProtoMessage() {}

func (x *ListMissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionsResponse.ProtoReflect.Descriptor instead.
func (*ListMissionsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ListMissionsResponse) GetMissions() []*MissionInfo {
	if x != nil {
		return x.Missions
	}
	return nil
}

func (x *ListMissionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// MissionInfo describes a mission.
type MissionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique mission identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// workflow_path is the path to the workflow file
	WorkflowPath string `protobuf:"bytes,2,opt,name=workflow_path,json=workflowPath,proto3" json:"workflow_path,omitempty"`
	// status is the mission status (running, completed, failed)
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// start_time is when the mission started (Unix timestamp)
	StartTime int64 `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// end_time is when the mission ended (Unix timestamp, 0 if running)
	EndTime int64 `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// finding_count is the number of findings discovered
	FindingCount  int32 `protobuf:"varint,6,opt,name=finding_count,json=findingCount,proto3" json:"finding_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionInfo) Reset() {
	*x = MissionInfo{}
	mi := &file_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionInfo) ProtoMessage() {}

func (x *MissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionInfo.ProtoReflect.Descriptor instead.
func (*MissionInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *MissionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MissionInfo) GetWorkflowPath() string {
	if x != nil {
		return x.WorkflowPath
	}
	return ""
}

func (x *MissionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MissionInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MissionInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *MissionInfo) GetFindingCount() int32 {
	if x != nil {
		return x.FindingCount
	}
	return 0
}

// ListAgentsRequest queries agent registry.
type ListAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind filters by component kind (empty = all agents)
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *ListAgentsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// ListAgentsResponse returns registered agents.
type ListAgentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agents is the list of registered agents
	Agents        []*AgentInfo `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// AgentInfo describes a registered agent.
type AgentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique agent identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the agent name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// kind is the component kind (always "agent")
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// version is the agent version
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// endpoint is the gRPC endpoint for the agent
	Endpoint string `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// capabilities lists agent capabilities
	Capabilities []string `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// health is the agent health status (healthy, unhealthy)
	Health string `protobuf:"bytes,7,opt,name=health,proto3" json:"health,omitempty"`
	// last_seen is when the agent was last seen (Unix timestamp)
	LastSeen      int64 `protobuf:"varint,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AgentInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentInfo) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *AgentInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// GetAgentStatusRequest queries a specific agent.
type GetAgentStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id is the unique agent identifier
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *GetAgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// AgentStatusResponse returns agent status.
type AgentStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent is the agent information
	Agent *AgentInfo `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// active indicates if the agent is currently executing a task
	Active bool `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	// current_task describes the active task (if any)
	CurrentTask string `protobuf:"bytes,3,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	// task_start_time is when the current task started (Unix timestamp)
	TaskStartTime int64 `protobuf:"varint,4,opt,name=task_start_time,json=taskStartTime,proto3" json:"task_start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusResponse) Reset() {
	*x = AgentStatusResponse{}
	mi := &file_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusResponse) ProtoMessage() {}

func (x *AgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusResponse.ProtoReflect.Descriptor instead.
func (*AgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *AgentStatusResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *AgentStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AgentStatusResponse) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

func (x *AgentStatusResponse) GetTaskStartTime() int64 {
	if x != nil {
		return x.TaskStartTime
	}
	return 0
}

// ListToolsRequest queries tool registry.
type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{18}
}

// ListToolsResponse returns registered tools.
type ListToolsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tools is the list of registered tools
	Tools         []*ToolInfo `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *ListToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolInfo describes a registered tool.
type ToolInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique tool identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the tool name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// version is the tool version
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// endpoint is the gRPC endpoint for the tool
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// description is the tool description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// health is the tool health status (healthy, unhealthy)
	Health string `protobuf:"bytes,6,opt,name=health,proto3" json:"health,omitempty"`
	// last_seen is when the tool was last seen (Unix timestamp)
	LastSeen      int64 `protobuf:"varint,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *ToolInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ToolInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ToolInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// ListPluginsRequest queries plugin registry.
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{21}
}

// ListPluginsResponse returns registered plugins.
type ListPluginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// plugins is the list of registered plugins
	Plugins       []*PluginInfo `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// PluginInfo describes a registered plugin.
type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique plugin identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the plugin name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// version is the plugin version
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// endpoint is the gRPC endpoint for the plugin
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// description is the plugin description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// health is the plugin health status (healthy, unhealthy)
	Health string `protobuf:"bytes,6,opt,name=health,proto3" json:"health,omitempty"`
	// last_seen is when the plugin was last seen (Unix timestamp)
	LastSeen      int64 `protobuf:"varint,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *PluginInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// RunAttackRequest executes an attack.
type RunAttackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target is the target URL or identifier
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// attack_type is the type of attack to execute
	AttackType string `protobuf:"bytes,2,opt,name=attack_type,json=attackType,proto3" json:"attack_type,omitempty"`
	// agent_id is the agent to use (optional, auto-select if empty)
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// payload_filter filters which payloads to use
	PayloadFilter string `protobuf:"bytes,4,opt,name=payload_filter,json=payloadFilter,proto3" json:"payload_filter,omitempty"`
	// options contains attack-specific options
	Options       map[string]string `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAttackRequest) Reset() {
	*x = RunAttackRequest{}
	mi := &file_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAttackRequest) ProtoMessage() {}

func (x *RunAttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAttackRequest.ProtoReflect.Descriptor instead.
func (*RunAttackRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *RunAttackRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunAttackRequest) GetAttackType() string {
	if x != nil {
		return x.AttackType
	}
	return ""
}

func (x *RunAttackRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunAttackRequest) GetPayloadFilter() string {
	if x != nil {
		return x.PayloadFilter
	}
	return ""
}

func (x *RunAttackRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// AttackEvent represents an attack execution event.
type AttackEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type identifies the type of event
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// timestamp is when the event occurred (Unix timestamp)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// attack_id is the unique attack identifier
	AttackId string `protobuf:"bytes,3,opt,name=attack_id,json=attackId,proto3" json:"attack_id,omitempty"`
	// message is a human-readable event message
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// data contains event-specific data (JSON-encoded)
	Data string `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// error contains error information if the event represents an error
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// finding describes a discovered finding (if applicable)
	Finding       *FindingInfo `protobuf:"bytes,7,opt,name=finding,proto3" json:"finding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackEvent) Reset() {
	*x = AttackEvent{}
	mi := &file_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackEvent) ProtoMessage() {}

func (x *AttackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackEvent.ProtoReflect.Descriptor instead.
func (*AttackEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *AttackEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AttackEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AttackEvent) GetAttackId() string {
	if x != nil {
		return x.AttackId
	}
	return ""
}

func (x *AttackEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AttackEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AttackEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AttackEvent) GetFinding() *FindingInfo {
	if x != nil {
		return x.Finding
	}
	return nil
}

// FindingInfo describes a discovered vulnerability.
type FindingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique finding identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// title is the finding title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// severity is the severity level (info, low, medium, high, critical)
	Severity string `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	// category is the finding category
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// description is the detailed finding description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// technique is the MITRE ATT&CK or ATLAS technique ID
	Technique string `protobuf:"bytes,6,opt,name=technique,proto3" json:"technique,omitempty"`
	// evidence contains supporting evidence
	Evidence string `protobuf:"bytes,7,opt,name=evidence,proto3" json:"evidence,omitempty"`
	// timestamp is when the finding was discovered (Unix timestamp)
	Timestamp     int64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingInfo) Reset() {
	*x = FindingInfo{}
	mi := &file_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingInfo) ProtoMessage() {}

func (x *FindingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingInfo.ProtoReflect.Descriptor instead.
func (*FindingInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *FindingInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindingInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindingInfo) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *FindingInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FindingInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindingInfo) GetTechnique() string {
	if x != nil {
		return x.Technique
	}
	return ""
}

func (x *FindingInfo) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *FindingInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// SubscribeRequest establishes an event stream.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_types filters which event types to receive (empty = all)
	EventTypes []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// mission_id filters to a specific mission (empty = all)
	MissionId     string `protobuf:"bytes,2,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_daemon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{27}
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *SubscribeRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

// Event represents a generic daemon event.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type identifies the type of event
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// timestamp is when the event occurred (Unix timestamp)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// source is the event source (mission, agent, daemon, etc.)
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// data contains event-specific data (JSON-encoded)
	Data string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// Specific event types (only one will be set)
	//
	// Types that are valid to be assigned to Event:
	//
	//	*Event_MissionEvent
	//	*Event_AttackEvent
	//	*Event_AgentEvent
	//	*Event_FindingEvent
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_daemon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{28}
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetMissionEvent() *MissionEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_MissionEvent); ok {
			return x.MissionEvent
		}
	}
	return nil
}

func (x *Event) GetAttackEvent() *AttackEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_AttackEvent); ok {
			return x.AttackEvent
		}
	}
	return nil
}

func (x *Event) GetAgentEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_AgentEvent); ok {
			return x.AgentEvent
		}
	}
	return nil
}

func (x *Event) GetFindingEvent() *FindingEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_FindingEvent); ok {
			return x.FindingEvent
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_MissionEvent struct {
	MissionEvent *MissionEvent `protobuf:"bytes,5,opt,name=mission_event,json=missionEvent,proto3,oneof"`
}

type Event_AttackEvent struct {
	AttackEvent *AttackEvent `protobuf:"bytes,6,opt,name=attack_event,json=attackEvent,proto3,oneof"`
}

type Event_AgentEvent struct {
	AgentEvent *AgentEvent `protobuf:"bytes,7,opt,name=agent_event,json=agentEvent,proto3,oneof"`
}

type Event_FindingEvent struct {
	FindingEvent *FindingEvent `protobuf:"bytes,8,opt,name=finding_event,json=findingEvent,proto3,oneof"`
}

func (*Event_MissionEvent) isEvent_Event() {}

func (*Event_AttackEvent) isEvent_Event() {}

func (*Event_AgentEvent) isEvent_Event() {}

func (*Event_FindingEvent) isEvent_Event() {}

// AgentEvent represents an agent lifecycle event.
type AgentEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type identifies the agent event type (registered, unregistered, health_change)
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// timestamp is when the event occurred (Unix timestamp)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// agent_id is the agent identifier
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// agent_name is the agent name
	AgentName string `protobuf:"bytes,4,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	// message is a human-readable message
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// data contains event-specific data (JSON-encoded)
	Data          string `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_daemon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{29}
}

func (x *AgentEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentEvent) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// FindingEvent represents a finding discovery event.
type FindingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type identifies the finding event type (discovered, updated)
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// timestamp is when the event occurred (Unix timestamp)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// finding is the finding information
	Finding *FindingInfo `protobuf:"bytes,3,opt,name=finding,proto3" json:"finding,omitempty"`
	// mission_id is the mission that discovered the finding
	MissionId     string `protobuf:"bytes,4,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingEvent) Reset() {
	*x = FindingEvent{}
	mi := &file_daemon_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingEvent) ProtoMessage() {}

func (x *FindingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingEvent.ProtoReflect.Descriptor instead.
func (*FindingEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{30}
}

func (x *FindingEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *FindingEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FindingEvent) GetFinding() *FindingInfo {
	if x != nil {
		return x.Finding
	}
	return nil
}

func (x *FindingEvent) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

// StartComponentRequest requests starting a component.
type StartComponentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the component kind ("agent", "tool", "plugin")
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// name is the component name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartComponentRequest) Reset() {
	*x = StartComponentRequest{}
	mi := &file_daemon_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartComponentRequest) ProtoMessage() {}

func (x *StartComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartComponentRequest.ProtoReflect.Descriptor instead.
func (*StartComponentRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{31}
}

func (x *StartComponentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StartComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// StartComponentResponse returns the result of starting a component.
type StartComponentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates if the component was started successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// pid is the process ID of the started component
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// port is the port the component is listening on
	Port int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// message provides additional context or error information
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// log_path is the path to the component's log file
	LogPath       string `protobuf:"bytes,5,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartComponentResponse) Reset() {
	*x = StartComponentResponse{}
	mi := &file_daemon_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartComponentResponse) ProtoMessage() {}

func (x *StartComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartComponentResponse.ProtoReflect.Descriptor instead.
func (*StartComponentResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{32}
}

func (x *StartComponentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartComponentResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StartComponentResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartComponentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartComponentResponse) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

// StopComponentRequest requests stopping a component.
type StopComponentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the component kind ("agent", "tool", "plugin")
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// name is the component name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// force indicates whether to skip graceful shutdown (SIGKILL instead of SIGTERM)
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopComponentRequest) Reset() {
	*x = StopComponentRequest{}
	mi := &file_daemon_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopComponentRequest) ProtoMessage() {}

func (x *StopComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopComponentRequest.ProtoReflect.Descriptor instead.
func (*StopComponentRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{33}
}

func (x *StopComponentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StopComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StopComponentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// StopComponentResponse returns the result of stopping a component.
type StopComponentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates if the component was stopped successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// stopped_count is the number of instances successfully stopped
	StoppedCount int32 `protobuf:"varint,2,opt,name=stopped_count,json=stoppedCount,proto3" json:"stopped_count,omitempty"`
	// total_count is the total number of instances that were running
	TotalCount int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// message provides additional context or error information
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopComponentResponse) Reset() {
	*x = StopComponentResponse{}
	mi := &file_daemon_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopComponentResponse) ProtoMessage() {}

func (x *StopComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopComponentResponse.ProtoReflect.Descriptor instead.
func (*StopComponentResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{34}
}

func (x *StopComponentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopComponentResponse) GetStoppedCount() int32 {
	if x != nil {
		return x.StoppedCount
	}
	return 0
}

func (x *StopComponentResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *StopComponentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\x10gibson.daemon.v1\"T\n" +
	"\x0eConnectRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"z\n" +
	"\x0fConnectResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fgrpc_address\x18\x03 \x01(\tR\vgrpcAddress\"\r\n" +
	"\vPingRequest\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x0f\n" +
	"\rStatusRequest\"\xfd\x02\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12!\n" +
	"\fgrpc_address\x18\x05 \x01(\tR\vgrpcAddress\x12#\n" +
	"\rregistry_type\x18\x06 \x01(\tR\fregistryType\x12#\n" +
	"\rregistry_addr\x18\a \x01(\tR\fregistryAddr\x12#\n" +
	"\rcallback_addr\x18\b \x01(\tR\fcallbackAddr\x12\x1f\n" +
	"\vagent_count\x18\t \x01(\x05R\n" +
	"agentCount\x12#\n" +
	"\rmission_count\x18\n" +
	" \x01(\x05R\fmissionCount\x120\n" +
	"\x14active_mission_count\x18\v \x01(\x05R\x12activeMissionCount\"\xe7\x01\n" +
	"\x11RunMissionRequest\x12#\n" +
	"\rworkflow_path\x18\x01 \x01(\tR\fworkflowPath\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x02 \x01(\tR\tmissionId\x12P\n" +
	"\tvariables\x18\x03 \x03(\v22.gibson.daemon.v1.RunMissionRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\fMissionEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x03 \x01(\tR\tmissionId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"I\n" +
	"\x12StopMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"I\n" +
	"\x13StopMissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x13ListMissionsRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"g\n" +
	"\x14ListMissionsResponse\x129\n" +
	"\bmissions\x18\x01 \x03(\v2\x1d.gibson.daemon.v1.MissionInfoR\bmissions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb9\x01\n" +
	"\vMissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rworkflow_path\x18\x02 \x01(\tR\fworkflowPath\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12#\n" +
	"\rfinding_count\x18\x06 \x01(\x05R\ffindingCount\"'\n" +
	"\x11ListAgentsRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"I\n" +
	"\x12ListAgentsResponse\x123\n" +
	"\x06agents\x18\x01 \x03(\v2\x1b.gibson.daemon.v1.AgentInfoR\x06agents\"\xd2\x01\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x16\n" +
	"\x06health\x18\a \x01(\tR\x06health\x12\x1b\n" +
	"\tlast_seen\x18\b \x01(\x03R\blastSeen\"2\n" +
	"\x15GetAgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xab\x01\n" +
	"\x13AgentStatusResponse\x121\n" +
	"\x05agent\x18\x01 \x01(\v2\x1b.gibson.daemon.v1.AgentInfoR\x05agent\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12!\n" +
	"\fcurrent_task\x18\x03 \x01(\tR\vcurrentTask\x12&\n" +
	"\x0ftask_start_time\x18\x04 \x01(\x03R\rtaskStartTime\"\x12\n" +
	"\x10ListToolsRequest\"E\n" +
	"\x11ListToolsResponse\x120\n" +
	"\x05tools\x18\x01 \x03(\v2\x1a.gibson.daemon.v1.ToolInfoR\x05tools\"\xbb\x01\n" +
	"\bToolInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06health\x18\x06 \x01(\tR\x06health\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\x03R\blastSeen\"\x14\n" +
	"\x12ListPluginsRequest\"M\n" +
	"\x13ListPluginsResponse\x126\n" +
	"\aplugins\x18\x01 \x03(\v2\x1c.gibson.daemon.v1.PluginInfoR\aplugins\"\xbd\x01\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06health\x18\x06 \x01(\tR\x06health\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\x03R\blastSeen\"\x94\x02\n" +
	"\x10RunAttackRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1f\n" +
	"\vattack_type\x18\x02 \x01(\tR\n" +
	"attackType\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12%\n" +
	"\x0epayload_filter\x18\x04 \x01(\tR\rpayloadFilter\x12I\n" +
	"\aoptions\x18\x05 \x03(\v2/.gibson.daemon.v1.RunAttackRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\vAttackEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tattack_id\x18\x03 \x01(\tR\battackId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x127\n" +
	"\afinding\x18\a \x01(\v2\x1d.gibson.daemon.v1.FindingInfoR\afinding\"\xe5\x01\n" +
	"\vFindingInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttechnique\x18\x06 \x01(\tR\ttechnique\x12\x1a\n" +
	"\bevidence\x18\a \x01(\tR\bevidence\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"R\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x02 \x01(\tR\tmissionId\"\x8c\x03\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12E\n" +
	"\rmission_event\x18\x05 \x01(\v2\x1e.gibson.daemon.v1.MissionEventH\x00R\fmissionEvent\x12B\n" +
	"\fattack_event\x18\x06 \x01(\v2\x1d.gibson.daemon.v1.AttackEventH\x00R\vattackEvent\x12?\n" +
	"\vagent_event\x18\a \x01(\v2\x1c.gibson.daemon.v1.AgentEventH\x00R\n" +
	"agentEvent\x12E\n" +
	"\rfinding_event\x18\b \x01(\v2\x1e.gibson.daemon.v1.FindingEventH\x00R\ffindingEventB\a\n" +
	"\x05event\"\xb1\x01\n" +
	"\n" +
	"AgentEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x04 \x01(\tR\tagentName\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\"\xa3\x01\n" +
	"\fFindingEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x127\n" +
	"\afinding\x18\x03 \x01(\v2\x1d.gibson.daemon.v1.FindingInfoR\afinding\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x04 \x01(\tR\tmissionId\"?\n" +
	"\x15StartComponentRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8d\x01\n" +
	"\x16StartComponentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x19\n" +
	"\blog_path\x18\x05 \x01(\tR\alogPath\"T\n" +
	"\x14StopComponentRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x91\x01\n" +
	"\x15StopComponentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rstopped_count\x18\x02 \x01(\x05R\fstoppedCount\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xd5\t\n" +
	"\rDaemonService\x12N\n" +
	"\aConnect\x12 .gibson.daemon.v1.ConnectRequest\x1a!.gibson.daemon.v1.ConnectResponse\x12E\n" +
	"\x04Ping\x12\x1d.gibson.daemon.v1.PingRequest\x1a\x1e.gibson.daemon.v1.PingResponse\x12K\n" +
	"\x06Status\x12\x1f.gibson.daemon.v1.StatusRequest\x1a .gibson.daemon.v1.StatusResponse\x12S\n" +
	"\n" +
	"RunMission\x12#.gibson.daemon.v1.RunMissionRequest\x1a\x1e.gibson.daemon.v1.MissionEvent0\x01\x12Z\n" +
	"\vStopMission\x12$.gibson.daemon.v1.StopMissionRequest\x1a%.gibson.daemon.v1.StopMissionResponse\x12]\n" +
	"\fListMissions\x12%.gibson.daemon.v1.ListMissionsRequest\x1a&.gibson.daemon.v1.ListMissionsResponse\x12W\n" +
	"\n" +
	"ListAgents\x12#.gibson.daemon.v1.ListAgentsRequest\x1a$.gibson.daemon.v1.ListAgentsResponse\x12`\n" +
	"\x0eGetAgentStatus\x12'.gibson.daemon.v1.GetAgentStatusRequest\x1a%.gibson.daemon.v1.AgentStatusResponse\x12T\n" +
	"\tListTools\x12\".gibson.daemon.v1.ListToolsRequest\x1a#.gibson.daemon.v1.ListToolsResponse\x12Z\n" +
	"\vListPlugins\x12$.gibson.daemon.v1.ListPluginsRequest\x1a%.gibson.daemon.v1.ListPluginsResponse\x12P\n" +
	"\tRunAttack\x12\".gibson.daemon.v1.RunAttackRequest\x1a\x1d.gibson.daemon.v1.AttackEvent0\x01\x12J\n" +
	"\tSubscribe\x12\".gibson.daemon.v1.SubscribeRequest\x1a\x17.gibson.daemon.v1.Event0\x01\x12c\n" +
	"\x0eStartComponent\x12'.gibson.daemon.v1.StartComponentRequest\x1a(.gibson.daemon.v1.StartComponentResponse\x12`\n" +
	"\rStopComponent\x12&.gibson.daemon.v1.StopComponentRequest\x1a'.gibson.daemon.v1.StopComponentResponseB7Z5github.com/zero-day-ai/gibson/internal/daemon/api;apib\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_daemon_proto_goTypes = []any{
	(*ConnectRequest)(nil),         // 0: gibson.daemon.v1.ConnectRequest
	(*ConnectResponse)(nil),        // 1: gibson.daemon.v1.ConnectResponse
	(*PingRequest)(nil),            // 2: gibson.daemon.v1.PingRequest
	(*PingResponse)(nil),           // 3: gibson.daemon.v1.PingResponse
	(*StatusRequest)(nil),          // 4: gibson.daemon.v1.StatusRequest
	(*StatusResponse)(nil),         // 5: gibson.daemon.v1.StatusResponse
	(*RunMissionRequest)(nil),      // 6: gibson.daemon.v1.RunMissionRequest
	(*MissionEvent)(nil),           // 7: gibson.daemon.v1.MissionEvent
	(*StopMissionRequest)(nil),     // 8: gibson.daemon.v1.StopMissionRequest
	(*StopMissionResponse)(nil),    // 9: gibson.daemon.v1.StopMissionResponse
	(*ListMissionsRequest)(nil),    // 10: gibson.daemon.v1.ListMissionsRequest
	(*ListMissionsResponse)(nil),   // 11: gibson.daemon.v1.ListMissionsResponse
	(*MissionInfo)(nil),            // 12: gibson.daemon.v1.MissionInfo
	(*ListAgentsRequest)(nil),      // 13: gibson.daemon.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),     // 14: gibson.daemon.v1.ListAgentsResponse
	(*AgentInfo)(nil),              // 15: gibson.daemon.v1.AgentInfo
	(*GetAgentStatusRequest)(nil),  // 16: gibson.daemon.v1.GetAgentStatusRequest
	(*AgentStatusResponse)(nil),    // 17: gibson.daemon.v1.AgentStatusResponse
	(*ListToolsRequest)(nil),       // 18: gibson.daemon.v1.ListToolsRequest
	(*ListToolsResponse)(nil),      // 19: gibson.daemon.v1.ListToolsResponse
	(*ToolInfo)(nil),               // 20: gibson.daemon.v1.ToolInfo
	(*ListPluginsRequest)(nil),     // 21: gibson.daemon.v1.ListPluginsRequest
	(*ListPluginsResponse)(nil),    // 22: gibson.daemon.v1.ListPluginsResponse
	(*PluginInfo)(nil),             // 23: gibson.daemon.v1.PluginInfo
	(*RunAttackRequest)(nil),       // 24: gibson.daemon.v1.RunAttackRequest
	(*AttackEvent)(nil),            // 25: gibson.daemon.v1.AttackEvent
	(*FindingInfo)(nil),            // 26: gibson.daemon.v1.FindingInfo
	(*SubscribeRequest)(nil),       // 27: gibson.daemon.v1.SubscribeRequest
	(*Event)(nil),                  // 28: gibson.daemon.v1.Event
	(*AgentEvent)(nil),             // 29: gibson.daemon.v1.AgentEvent
	(*FindingEvent)(nil),           // 30: gibson.daemon.v1.FindingEvent
	(*StartComponentRequest)(nil),  // 31: gibson.daemon.v1.StartComponentRequest
	(*StartComponentResponse)(nil), // 32: gibson.daemon.v1.StartComponentResponse
	(*StopComponentRequest)(nil),   // 33: gibson.daemon.v1.StopComponentRequest
	(*StopComponentResponse)(nil),  // 34: gibson.daemon.v1.StopComponentResponse
	nil,                            // 35: gibson.daemon.v1.RunMissionRequest.VariablesEntry
	nil,                            // 36: gibson.daemon.v1.RunAttackRequest.OptionsEntry
}
var file_daemon_proto_depIdxs = []int32{
	35, // 0: gibson.daemon.v1.RunMissionRequest.variables:type_name -> gibson.daemon.v1.RunMissionRequest.VariablesEntry
	12, // 1: gibson.daemon.v1.ListMissionsResponse.missions:type_name -> gibson.daemon.v1.MissionInfo
	15, // 2: gibson.daemon.v1.ListAgentsResponse.agents:type_name -> gibson.daemon.v1.AgentInfo
	15, // 3: gibson.daemon.v1.AgentStatusResponse.agent:type_name -> gibson.daemon.v1.AgentInfo
	20, // 4: gibson.daemon.v1.ListToolsResponse.tools:type_name -> gibson.daemon.v1.ToolInfo
	23, // 5: gibson.daemon.v1.ListPluginsResponse.plugins:type_name -> gibson.daemon.v1.PluginInfo
	36, // 6: gibson.daemon.v1.RunAttackRequest.options:type_name -> gibson.daemon.v1.RunAttackRequest.OptionsEntry
	26, // 7: gibson.daemon.v1.AttackEvent.finding:type_name -> gibson.daemon.v1.FindingInfo
	7,  // 8: gibson.daemon.v1.Event.mission_event:type_name -> gibson.daemon.v1.MissionEvent
	25, // 9: gibson.daemon.v1.Event.attack_event:type_name -> gibson.daemon.v1.AttackEvent
	29, // 10: gibson.daemon.v1.Event.agent_event:type_name -> gibson.daemon.v1.AgentEvent
	30, // 11: gibson.daemon.v1.Event.finding_event:type_name -> gibson.daemon.v1.FindingEvent
	26, // 12: gibson.daemon.v1.FindingEvent.finding:type_name -> gibson.daemon.v1.FindingInfo
	0,  // 13: gibson.daemon.v1.DaemonService.Connect:input_type -> gibson.daemon.v1.ConnectRequest
	2,  // 14: gibson.daemon.v1.DaemonService.Ping:input_type -> gibson.daemon.v1.PingRequest
	4,  // 15: gibson.daemon.v1.DaemonService.Status:input_type -> gibson.daemon.v1.StatusRequest
	6,  // 16: gibson.daemon.v1.DaemonService.RunMission:input_type -> gibson.daemon.v1.RunMissionRequest
	8,  // 17: gibson.daemon.v1.DaemonService.StopMission:input_type -> gibson.daemon.v1.StopMissionRequest
	10, // 18: gibson.daemon.v1.DaemonService.ListMissions:input_type -> gibson.daemon.v1.ListMissionsRequest
	13, // 19: gibson.daemon.v1.DaemonService.ListAgents:input_type -> gibson.daemon.v1.ListAgentsRequest
	16, // 20: gibson.daemon.v1.DaemonService.GetAgentStatus:input_type -> gibson.daemon.v1.GetAgentStatusRequest
	18, // 21: gibson.daemon.v1.DaemonService.ListTools:input_type -> gibson.daemon.v1.ListToolsRequest
	21, // 22: gibson.daemon.v1.DaemonService.ListPlugins:input_type -> gibson.daemon.v1.ListPluginsRequest
	24, // 23: gibson.daemon.v1.DaemonService.RunAttack:input_type -> gibson.daemon.v1.RunAttackRequest
	27, // 24: gibson.daemon.v1.DaemonService.Subscribe:input_type -> gibson.daemon.v1.SubscribeRequest
	31, // 25: gibson.daemon.v1.DaemonService.StartComponent:input_type -> gibson.daemon.v1.StartComponentRequest
	33, // 26: gibson.daemon.v1.DaemonService.StopComponent:input_type -> gibson.daemon.v1.StopComponentRequest
	1,  // 27: gibson.daemon.v1.DaemonService.Connect:output_type -> gibson.daemon.v1.ConnectResponse
	3,  // 28: gibson.daemon.v1.DaemonService.Ping:output_type -> gibson.daemon.v1.PingResponse
	5,  // 29: gibson.daemon.v1.DaemonService.Status:output_type -> gibson.daemon.v1.StatusResponse
	7,  // 30: gibson.daemon.v1.DaemonService.RunMission:output_type -> gibson.daemon.v1.MissionEvent
	9,  // 31: gibson.daemon.v1.DaemonService.StopMission:output_type -> gibson.daemon.v1.StopMissionResponse
	11, // 32: gibson.daemon.v1.DaemonService.ListMissions:output_type -> gibson.daemon.v1.ListMissionsResponse
	14, // 33: gibson.daemon.v1.DaemonService.ListAgents:output_type -> gibson.daemon.v1.ListAgentsResponse
	17, // 34: gibson.daemon.v1.DaemonService.GetAgentStatus:output_type -> gibson.daemon.v1.AgentStatusResponse
	19, // 35: gibson.daemon.v1.DaemonService.ListTools:output_type -> gibson.daemon.v1.ListToolsResponse
	22, // 36: gibson.daemon.v1.DaemonService.ListPlugins:output_type -> gibson.daemon.v1.ListPluginsResponse
	25, // 37: gibson.daemon.v1.DaemonService.RunAttack:output_type -> gibson.daemon.v1.AttackEvent
	28, // 38: gibson.daemon.v1.DaemonService.Subscribe:output_type -> gibson.daemon.v1.Event
	32, // 39: gibson.daemon.v1.DaemonService.StartComponent:output_type -> gibson.daemon.v1.StartComponentResponse
	34, // 40: gibson.daemon.v1.DaemonService.StopComponent:output_type -> gibson.daemon.v1.StopComponentResponse
	27, // [27:41] is the sub-list for method output_type
	13, // [13:27] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	file_daemon_proto_msgTypes[28].OneofWrappers = []any{
		(*Event_MissionEvent)(nil),
		(*Event_AttackEvent)(nil),
		(*Event_AgentEvent)(nil),
		(*Event_FindingEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
